---
name: WMBus Meters Runner
version: 0.0.9
slug: wmbus-metters-runner
description: Addon to run wmbusmeters periodically to collect data from wmbus meters.
url: https://github.com/Unlink/hassio_addons/addon-wmbusmeters-runner
init: false
privileged:
  - SYS_RAWIO
  - SYS_ADMIN
devices:
  - /dev/bus/usb
arch:
  - aarch64
  - amd64
  - armv7
options:
  log_level: info
  reading_interval_minutes: 30
  usb_device_filter: "RTL"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  reading_interval_minutes: int(1,1440)
  usb_device_filter: str
