---
name: WMBus Meters Runner
version: dev
slug: wmbus-metters-runner
description: Addon to run wmbusmeters periodically to collect data from wmbus meters.
url: https://github.com/Unlink/hassio_addons/addon-wmbusmeters-runner
init: false
arch:
  - aarch64
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
